#!/usr/bin/env node
// Generate the client types both apps decode with, from contracts/openapi.yaml.
//
// native-contract.mjs DETECTS drift between the routes and the Swift structs. This
// PREVENTS a whole class of it: the Swift and TypeScript shapes stop being two hand-kept
// transcriptions of a third thing and become output of one declaration.
//
// Deliberately hand-rolled rather than a general OpenAPI generator. The spec is six
// paths; a generator would be a large dependency producing code nobody reads, and the
// output here is meant to be read in review — that is where a breaking change gets
// noticed by a person.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { parse } from "yaml";

const spec = parse(readFileSync("contracts/openapi.yaml", "utf8"));
const schemas = spec.components?.schemas ?? {};
if (Object.keys(schemas).length === 0) { console.error("FAIL  the spec declares no schemas"); process.exit(1); }

const banner = (lang) => [
  `${lang} GENERATED by scripts/contracts/generate.mjs from contracts/openapi.yaml`,
  `${lang} DO NOT EDIT. Edit the spec and re-run; contracts-fresh.mjs fails the build if`,
  `${lang} this file and the spec disagree.`,
  `${lang}`,
  `${lang} API version ${spec.info.version}`,
].join("\n");

const ref = (s) => (s?.$ref ? s.$ref.split("/").pop() : null);

// ── TypeScript ───────────────────────────────────────────────────────────────
function tsType(s) {
  const r = ref(s);
  if (r) return r;
  if (s.enum) return s.enum.filter((v) => v !== null).map((v) => JSON.stringify(v)).join(" | ");
  switch (s.type) {
    case "string": return "string";
    case "integer": case "number": return "number";
    case "boolean": return "boolean";
    case "array": return `${tsType(s.items ?? {})}[]`;
    case "object": {
      const props = Object.entries(s.properties ?? {});
      if (!props.length) return "Record<string, unknown>";
      const req = new Set(s.required ?? []);
      return `{ ${props.map(([k, v]) => `${k}${req.has(k) ? "" : "?"}: ${tsType(v)}${v.nullable ? " | null" : ""}`).join("; ")} }`;
    }
    default: return "unknown";
  }
}
const ts = [banner("//"), ""];
for (const [name, s] of Object.entries(schemas)) {
  if (s.enum) { ts.push(`export type ${name} = ${s.enum.filter((v) => v !== null).map((v) => JSON.stringify(v)).join(" | ")};`, ""); continue; }
  const req = new Set(s.required ?? []);
  ts.push(`export interface ${name} {`);
  for (const [k, v] of Object.entries(s.properties ?? {})) {
    if (v.description) ts.push(`  /** ${String(v.description).trim().replace(/\s+/g, " ")} */`);
    ts.push(`  ${k}${req.has(k) ? "" : "?"}: ${tsType(v)}${v.nullable ? " | null" : ""};`);
  }
  ts.push("}", "");
}
mkdirSync("contracts/generated", { recursive: true });
writeFileSync("contracts/generated/types.ts", ts.join("\n"));

// ── Swift ────────────────────────────────────────────────────────────────────
// Everything optional except the fields the spec marks required. A missing key on a
// non-optional property THROWS in Swift and stops cloud sync on installed builds, so the
// spec's `required` list is the only thing allowed to make a property non-optional.
function swiftType(s) {
  const r = ref(s);
  if (r) return r;
  if (s.enum) return "String";
  switch (s.type) {
    case "string": return "String";
    case "integer": return "Int";
    case "number": return "Double";
    case "boolean": return "Bool";
    case "array": return `[${swiftType(s.items ?? {})}]`;
    case "object": return "AnyCodableObject";
    default: return "String";
  }
}
const sw = [banner("//"), "", "import Foundation", ""];
sw.push("/// A JSON object whose shape the spec does not pin down.");
sw.push("public typealias AnyCodableObject = [String: String]", "");
for (const [name, s] of Object.entries(schemas)) {
  if (s.enum) {
    sw.push(`public enum ${name}: String, Codable {`);
    for (const v of s.enum.filter(Boolean)) sw.push(`    case ${v} = ${JSON.stringify(v)}`);
    // An unrecognised value must not throw: the server may add a state before this build
    // is updated, and a decode failure there stops sync entirely.
    sw.push(`    public init(from decoder: Decoder) throws {`);
    sw.push(`        let raw = try decoder.singleValueContainer().decode(String.self)`);
    sw.push(`        self = ${name}(rawValue: raw) ?? .${s.enum.filter(Boolean).slice(-1)[0]}`);
    sw.push(`    }`, "}", "");
    continue;
  }
  const req = new Set(s.required ?? []);
  sw.push(`public struct ${name}: Codable {`);
  for (const [k, v] of Object.entries(s.properties ?? {})) {
    if (v.description) sw.push(`    /// ${String(v.description).trim().replace(/\s+/g, " ")}`);
    const opt = req.has(k) && !v.nullable ? "" : "?";
    sw.push(`    public var ${k}: ${swiftType(v)}${opt}`);
  }
  sw.push("}", "");
}
writeFileSync("contracts/generated/Contracts.swift", sw.join("\n"));

// --lock re-records the agreed surface. Deliberately a separate, explicit act: it is the
// moment somebody says "yes, this contract change is intended".
if (process.argv.includes("--lock")) {
  const surface = { paths: {}, schemas: {} };
  for (const [p, ops] of Object.entries(spec.paths ?? {})) {
    surface.paths[p] = Object.keys(ops).filter((k) => ["get","post","put","patch","delete"].includes(k)).sort();
  }
  for (const [n, sc] of Object.entries(schemas)) {
    surface.schemas[n] = {
      properties: Object.keys(sc.properties ?? {}).sort(),
      required: [...(sc.required ?? [])].sort(),
      ...(sc.enum ? { enum: [...sc.enum].sort() } : {}),
    };
  }
  writeFileSync("contracts/surface.lock.json", JSON.stringify(surface, null, 2) + "\n");
  console.log("  surface re-locked -> contracts/surface.lock.json");
}

console.log(`  ${Object.keys(schemas).length} schemas -> contracts/generated/types.ts and Contracts.swift`);
